services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Africa/Nairobi
      - PORTAINER_THEME=dark
      - com.centurylinklabs.watchtower.enable=true    
    networks:
      internal_network:
        ipv4_address: 172.30.0.10
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "5m"

  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - TZ=Africa/Nairobi
      - com.centurylinklabs.watchtower.enable=true    
    networks:
      - internal_network
    depends_on:
      - portainer

networks:
  internal_network:
    external: true
